### ISSUE TITLE
Registering Mouse Gesture

### ISSUE THREAD

**Issue by palagroup** [chromoly/blender_mouse_gesture#1]
Hi @chromoly ,
when I try to install this module, I got the following error:  

```
_File "C:\Program Files\Blender Foundation\Blender\2.77\scripts\addons\blender_
mouse_gesture-master\utils.py", line 431, in __get_wm_prop
    self.bl_idname.replace('.', '_'))
AttributeError: 'AddonRegisterInformation' object has no attribute '♠'_
```

The object self.idname doesn't have Any attributes at all.

I congratulate you Chromoly, I was using your plugin, and updating it from blender versions since 2.6, but I can't fix it now in this version.

Cheers.

**Comment by chromoly** [comment]
OK!
直した！

**Comment by palagroup** [comment]
@chromoly do you have an email address to have your contact?

**Comment by chromoly** [comment]
chromolytube@gmail.com

I'm not good at English, Sorry.
